services:
  mongo:
    image: mongo:6
    container_name: mongo-expensy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:7
    container_name: redis-expensy
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "someredispassword"]

  backend:
    build: ./expensy_backend
    container_name: expensy-backend
    ports:
      - "8706:8706"
    environment:
      PORT: 8706
      DATABASE_URI: mongodb://root:example@mongo:27017/expensy?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: someredispassword
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./expensy_frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8706
    container_name: expensy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
