apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensy-backend
  template:
    metadata:
      labels:
        app: expensy-backend
    spec:
      containers:
      - name: backend
        image: anne2693/expensy-backend:latest
        ports:
        - containerPort: 8706
        env:
        - name: PORT
          value: "8706"
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URI
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: expensy-backend
spec:
  type: ClusterIP
  selector:
    app: expensy-backend
  ports:
    - port: 8706
      targetPort: 8706
