apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-frontend
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensy-frontend
  template:
    metadata:
      labels:
        app: expensy-frontend
    spec:
      containers:
        - name: expensy-frontend
          image: anne2693/expensy-frontend:latest  # CI/CD should overwrite
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: expensy-frontend
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: expensy-frontend
  ports:
    - port: 80
      targetPort: 3000
