apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-frontend
  namespace: expensy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensy-frontend
  template:
    metadata:
      labels:
        app: expensy-frontend
    spec:
      containers:
      - name: frontend
        image: anne2693/expensy-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: expensy-secrets
              key: API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: expensy-frontend
  namespace: expensy
spec:
  type: LoadBalancer
  selector:
    app: expensy-frontend
  ports:
    - port: 80
      targetPort: 3000
