apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress
  namespace: expensy-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nip.io  # Replace with your domain or test with nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expensy-frontend
                port:
                  number: 80
