apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: expensy
type: Opaque
stringData:
  mongo_user: ${MONGO_USER}
  mongo_pass: ${MONGO_PASS}
  redis_password: ${REDIS_PASSWORD}
  database_uri: ${DATABASE_URI}
  API_URL: ${API_URL}
  