apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: expensy
type: Opaque
stringData:
  API_URL: ${API_URL}
  DATABASE_URI: ${DATABASE_URI}
  MONGO_USER: ${MONGO_USER}
  MONGO_PASS: ${MONGO_PASS}
  NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
  REDIS_PASSWORD: ${REDIS_PASSWORD}